version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - /etc/redis/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    command: redis-server --requirepass ${REDIS_PASSWORD} --port 6379
    networks:
      - my_network

  application:
    container_name: app
    image: ${DOCKER_REPO}:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - my_network

networks:
  my_network:
    external: true