version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server /usr/local/conf/redis.conf
    networks:
      - my_network

  application:
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - my_network

networks:
  my_network:
    external: true